# Generated by Django 5.2.6 on 2025-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/'),
        ),
    ]
