# Generated by Django 5.2.6 on 2025-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='image/'),
        ),
    ]
